# Generated by Django 4.0.3 on 2022-04-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slugField',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
